# Generated by Django 5.0.6 on 2024-10-22 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarAlarms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speedAlertEnabled', models.BooleanField(default=False)),
                ('speedNotificationEnabled', models.BooleanField(default=False)),
                ('vibrationAlertEnabled', models.BooleanField(default=True)),
                ('vibrationNotificationEnabled', models.BooleanField(default=True)),
                ('fuelAlertEnabled', models.BooleanField(default=False)),
                ('fuelNotificationEnabled', models.BooleanField(default=False)),
                ('rapidAccelerationAlertEnabled', models.BooleanField(default=True)),
                ('rapidAccelerationNotificationEnabled', models.BooleanField(default=True)),
                ('harshBrakingAlertEnabled', models.BooleanField(default=True)),
                ('harshBrakingNotificationEnabled', models.BooleanField(default=True)),
                ('hardBrakingAlertEnabled', models.BooleanField(default=False)),
                ('hardBrakingNotificationEnabled', models.BooleanField(default=False)),
                ('collisionDetectionAlertEnabled', models.BooleanField(default=True)),
                ('collisionDetectionNotificationEnabled', models.BooleanField(default=False)),
                ('aggressiveSteeringAlertEnabled', models.BooleanField(default=False)),
                ('aggressiveSteeringNotificationEnabled', models.BooleanField(default=False)),
                ('ignitionStatusAlertEnabled', models.BooleanField(default=False)),
                ('ignitionStatusNotificationEnabled', models.BooleanField(default=False)),
                ('batteryAlertEnabled', models.BooleanField(default=False)),
                ('batteryNotificationEnabled', models.BooleanField(default=False)),
                ('batteryChargingNotificationEnabled', models.BooleanField(default=True)),
                ('batteryVoltageAlertEnabled', models.BooleanField(default=True)),
                ('batteryVoltageNotificationEnabled', models.BooleanField(default=True)),
                ('tamperAlertAlertEnabled', models.BooleanField(default=True)),
                ('tamperAlertNotificationEnabled', models.BooleanField(default=True)),
                ('batteryModeEnabled', models.BooleanField(default=True)),
                ('powerSavingModeEnabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_type_id', models.IntegerField()),
                ('fuelCalid', models.CharField(max_length=255, null=True)),
                ('fuelThreshold', models.FloatField(default=0)),
                ('batteryCalid', models.CharField(max_length=255, null=True)),
                ('batteryThreshold', models.FloatField(default=0)),
                ('speedCalid', models.CharField(max_length=255, null=True)),
                ('speedThreshold', models.FloatField(default=0)),
                ('hardBrakingCalid', models.CharField(max_length=255, null=True)),
                ('hardBrakingSensitivity', models.CharField(default='moderate', max_length=255, null=True)),
                ('rapidAccelerationCalid', models.CharField(max_length=255, null=True)),
                ('rapidAccelerationSensitivity', models.CharField(default='moderate', max_length=255, null=True)),
                ('batteryMode', models.CharField(default='active', max_length=255, null=True)),
                ('powerModeType', models.CharField(blank=True, default='1', max_length=255, null=True)),
                ('ident', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('unselected', 'Unselected')], max_length=10)),
                ('notificationCount', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceAlarms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('radius', models.CharField(blank=True, max_length=255, null=True)),
                ('alertOnEnter', models.BooleanField(default=True)),
                ('alertOnExit', models.BooleanField(default=True)),
                ('alertOnNotification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicleImage', models.ImageField(blank=True, default='vehicle_images/black-car-vector.png', null=True, upload_to='vehicle_images/')),
                ('vinNumber', models.CharField(max_length=17)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=255)),
                ('nickName', models.CharField(blank=True, max_length=255, null=True)),
                ('licensePlate', models.CharField(blank=True, max_length=255, null=True)),
                ('odometerReading', models.CharField(blank=True, max_length=255, null=True)),
                ('numberVehicle', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_car', to=settings.AUTH_USER_MODEL)),
                ('CarAlarms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CarAlarms', to='devices.caralarms')),
            ],
        ),
        migrations.CreateModel(
            name='UserCarsWithDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_selected_by_user', to='devices.car')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_selected_by_car', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='UserSelectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_selected_by_user', to='devices.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_device', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
