# Generated by Django 5.0.6 on 2024-10-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caralarms',
            name='collisionDetectionAlertEnabled',
        ),
        migrations.RemoveField(
            model_name='caralarms',
            name='collisionDetectionNotificationEnabled',
        ),
    ]
