# Generated by Django 5.0.6 on 2024-10-31 10:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_caralarms_collisiondetectionalertenabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeId',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deviceName', models.CharField(max_length=255)),
                ('deviceTypeId', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
