# Generated by Django 5.0.6 on 2024-10-22 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBatchUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to='device_batch_uploads/')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned')], default='unassigned', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'safelink'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceBatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by_user', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'role__in': ['agency', 'dealer_super_admin', 'dealer_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_user', to=settings.AUTH_USER_MODEL)),
                ('previous_assignment', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['agency', 'dealer_super_admin', 'dealer_admin']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_previous_user', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devicebatchupload')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=255, null=True, unique=True)),
                ('sim_card', models.CharField(max_length=255, null=True)),
                ('iccid', models.CharField(max_length=255, null=True)),
                ('serial_number', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('upload', models.BooleanField(default=False, null=True)),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('monitor', 'monitor'), ('notmonitor', 'notmonitor')], default='notmonitor', max_length=10)),
                ('installation_status', models.CharField(choices=[('uninstall', 'Uninstall'), ('pending', 'Pending'), ('installed', 'Installed')], default='uninstall', max_length=10)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devicebatchupload')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceVehicleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_purchases', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='devices.device')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sales', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_sales', to='devices.car')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
