# Generated by Django 5.0.6 on 2024-11-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushNotification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmtoken',
            name='timezone',
            field=models.CharField(default='America/Los_Angeles', max_length=50),
        ),
    ]
